# Generated by Django 4.2 on 2023-11-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=75)),
                ('location', models.CharField(blank=True, max_length=75)),
                ('bio', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
