# Generated by Django 4.2.7 on 2023-12-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
