# Generated by Django 4.2.7 on 2023-12-04 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_profile_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="userref",
            new_name="user",
        ),
    ]
