# Generated by Django 4.2.7 on 2023-12-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_rename_userref_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
