# Generated by Django 4.2.7 on 2023-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
