# Generated by Django 4.2.7 on 2023-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_alter_profile_github_url_alter_profile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
