# Generated by Django 4.2.7 on 2023-12-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0007_alter_profile_github_url_alter_profile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
