# Generated by Django 4.2.7 on 2023-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0009_alter_profile_bio_alter_profile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
