# Generated by Django 4.2.7 on 2023-11-30 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=75, validators=[django.core.validators.EmailValidator]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
