# Generated by Django 4.2.7 on 2023-11-30 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=75, validators=[django.core.validators.EmailValidator]
            ),
        ),
    ]
