# Generated by Django 4.2.7 on 2023-12-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                default="http://www.dradha.co/profile-images/avatar_osteospermum.jpg",
                max_length=300,
            ),
        ),
    ]
