# Generated by Django 4.2.7 on 2023-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0005_user_oauth_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="oauth_login",
            field=models.CharField(default="False", max_length=20),
        ),
    ]
