# Generated by Django 4.2.7 on 2023-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0009_alter_user_oauth_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(
                blank=True,
                default="http://www.dradha.co/profile-images/avatar_osteospermum.jpg",
                max_length=300,
            ),
        ),
    ]
