# Generated by Django 4.2.7 on 2023-12-08 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0011_alter_user_oauth_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=75,
                validators=[django.core.validators.EmailValidator],
            ),
        ),
    ]
