# Generated by Django 4.2.7 on 2023-12-08 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0012_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
    ]
