# Generated by Django 4.2.7 on 2023-12-08 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0013_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
